### ISSUE TITLE
Gumpy want access gimmey gimmey gimmey

### ISSUE THREAD

**Issue by mynameisgump** [fogo-sh/CSBWiki#7]
### Username

Gump

### Account owner

Gump the Rotator of Shapes

**Comment by jackharrhy** [comment]
gumpy gump gump gump gump!

**Comment by jackharrhy** [comment]
![image](https://user-images.githubusercontent.com/6486417/230387463-80f756d6-ee09-48b4-b641-e8922d073a64.png)

**Comment by mynameisgump** [comment]
jajajaaaja jajajaaa jaaajajaaaja jaaajajaaa 
jaaajajaaajaaa jaaajaaajaaa jajajaaa 
jajaaajaaajaaa jajaaa jaaajajaaaja jaaajajaaa

**Comment by mynameisgump** [comment]
ARE YOU NOT ENTERTAINED
